name: Build TOC daily

on:
  schedule:
    - cron: '7 3 * * *'  # ריצה יומית ~06:07 שעון ישראל בקיץ
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install
        run: npm ci || npm i

      - name: Build toc.json
        run: npm run build

      - name: Commit & push
        run: |
          git config user.name "bot"
          git config user.email "bot@users.noreply.github.com"
          git add docs/toc.json
          git commit -m "chore: daily toc update" || echo "no changes"
          git push
